import { IOreumState } from '@typings/db';
import { time } from 'console';
import { atom } from 'recoil';

export interface ITodo {
  id: number;
  text: string;
}

export interface IToDoState {
  [key: string]: ITodo[];
}

export const toDoState = atom<IToDoState>({
  key: 'toDo',
  default: {
    차동차조: [{ id: 1, text: '창진' }],
    식당조: [
      { id: 2, text: '윤진' },
      { id: 3, text: '택준' },
    ],
    준비물조: [{ id: 4, text: '용익' }],
  },
});

export const oreumState = atom<IOreumState[]>({
  key: 'oreum',
  default: [
    {
      id: 1,
      title: '제주시에서 만나서 매주 오름 가실분~',
      description:
        '제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~',
      simpledec: '노형동 근처 매주 주말',
      area: '제주시',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 2,
      title: '한경쪽 오름 투어 가보실분 구합니다',
      description:
        '한경 근처에 사시는분 같이 놀아요한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요',
      simpledec: '한경면에서 ㄱㄱㄱ',
      area: '한경면',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 3,
      title: '서귀포시에서 만나서 매주 오름 가실분~',
      description: '서귀포에 있는 오름 돌아 다니실분~',
      simpledec: '서귀포 이마트에서 만남',
      area: '서귀포시',
      email: 'test12@naver.com',
      img: 'img/bg3.jpg',
    },
    {
      id: 4,
      title: '대정사시는분~',
      description: '대정에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '대정에서 ㄱㄱ',
      area: '대정읍',
      email: 'test12@naver.com',
      img: 'img/bg4.jpg',
    },
    {
      id: 5,
      title: '중문 사시는분 같이 놀러다녀요',
      description: '중문에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 중문에서 출발',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg5.jpg',
    },
    {
      id: 6,
      title: '안덕 사시는분 같이 놀러다녀요',
      description: '안덕에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 안덕에서 출발',
      area: '안덕면',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 7,
      title: '남원에서 만나서 매주 오름 가보실분 구합니다',
      description: '남원에서 만나서 매주 주말에 ㄱㄱㄱㄱㄱㄱㄱㄱ',
      simpledec: '남원 만남 ㄱㄱ',
      area: '남원읍',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 8,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '표선면',
      email: 'test12@naver.com',
      img: 'img/bg3.jpg',
    },
    {
      id: 9,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '성산읍',
      email: 'test12@naver.com',
      img: 'img/bg4.jpg',
    },
    {
      id: 10,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg5.jpg',
    },
    {
      id: 11,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 12,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 13,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg3.jpg',
    },
    {
      id: 14,
      title: '가나다라마바사',
      description: '설명설명',
      simpledec: '간단설명',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg4.jpg',
    },
    {
      id: 15,
      title: '제주시에서 만나서 매주 오름 가실분~',
      description:
        '제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~',
      simpledec: '노형동 근처 매주 주말',
      area: '제주시',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 16,
      title: '한경쪽 오름 투어 가보실분 구합니다',
      description:
        '한경 근처에 사시는분 같이 놀아요한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요',
      simpledec: '한경면에서 ㄱㄱㄱ',
      area: '한경면',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 17,
      title: '서귀포시에서 만나서 매주 오름 가실분~',
      description: '서귀포에 있는 오름 돌아 다니실분~',
      simpledec: '서귀포 이마트에서 만남',
      area: '서귀포시',
      email: 'test12@naver.com',
      img: 'img/bg3.jpg',
    },
    {
      id: 18,
      title: '대정사시는분~',
      description: '대정에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '대정에서 ㄱㄱ',
      area: '대정읍',
      email: 'test12@naver.com',
      img: 'img/bg4.jpg',
    },
    {
      id: 19,
      title: '중문 사시는분 같이 놀러다녀요',
      description: '중문에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 중문에서 출발',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg5.jpg',
    },
    {
      id: 20,
      title: '안덕 사시는분 같이 놀러다녀요',
      description: '안덕에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 안덕에서 출발',
      area: '안덕면',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 21,
      title: '남원에서 만나서 매주 오름 가보실분 구합니다',
      description: '남원에서 만나서 매주 주말에 ㄱㄱㄱㄱㄱㄱㄱㄱ',
      simpledec: '남원 만남 ㄱㄱ',
      area: '남원읍',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 22,
      title: '제주시에서 만나서 매주 오름 가실분~',
      description:
        '제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~',
      simpledec: '노형동 근처 매주 주말',
      area: '제주시',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 23,
      title: '한경쪽 오름 투어 가보실분 구합니다',
      description:
        '한경 근처에 사시는분 같이 놀아요한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요',
      simpledec: '한경면에서 ㄱㄱㄱ',
      area: '한경면',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 24,
      title: '서귀포시에서 만나서 매주 오름 가실분~',
      description: '서귀포에 있는 오름 돌아 다니실분~',
      simpledec: '서귀포 이마트에서 만남',
      area: '서귀포시',
      email: 'test12@naver.com',
      img: 'img/bg3.jpg',
    },
    {
      id: 25,
      title: '대정사시는분~',
      description: '대정에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '대정에서 ㄱㄱ',
      area: '대정읍',
      email: 'test12@naver.com',
      img: 'img/bg4.jpg',
    },
    {
      id: 26,
      title: '중문 사시는분 같이 놀러다녀요',
      description: '중문에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 중문에서 출발',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg5.jpg',
    },
    {
      id: 27,
      title: '안덕 사시는분 같이 놀러다녀요',
      description: '안덕에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 안덕에서 출발',
      area: '안덕면',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 28,
      title: '남원에서 만나서 매주 오름 가보실분 구합니다',
      description: '남원에서 만나서 매주 주말에 ㄱㄱㄱㄱㄱㄱㄱㄱ',
      simpledec: '남원 만남 ㄱㄱ',
      area: '남원읍',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 29,
      title: '제주시에서 만나서 매주 오름 가실분~',
      description:
        '제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~제주시에서 만나서 매주 오름 가실분~',
      simpledec: '노형동 근처 매주 주말',
      area: '제주시',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 30,
      title: '한경쪽 오름 투어 가보실분 구합니다',
      description:
        '한경 근처에 사시는분 같이 놀아요한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요 한경 근처에 사시는분 같이 놀아요',
      simpledec: '한경면에서 ㄱㄱㄱ',
      area: '한경면',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 31,
      title: '서귀포시에서 만나서 매주 오름 가실분~',
      description: '서귀포에 있는 오름 돌아 다니실분~',
      simpledec: '서귀포 이마트에서 만남',
      area: '서귀포시',
      email: 'test12@naver.com',
      img: 'img/bg3.jpg',
    },
    {
      id: 32,
      title: '대정사시는분~',
      description: '대정에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '대정에서 ㄱㄱ',
      area: '대정읍',
      email: 'test12@naver.com',
      img: 'img/bg4.jpg',
    },
    {
      id: 33,
      title: '중문 사시는분 같이 놀러다녀요',
      description: '중문에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 중문에서 출발',
      area: '중문',
      email: 'test12@naver.com',
      img: 'img/bg5.jpg',
    },
    {
      id: 34,
      title: '안덕 사시는분 같이 놀러다녀요',
      description: '안덕에서 만나서 매주 주말에 오름 투어 다니실분 구합니다~~~',
      simpledec: '2주에 한번 안덕에서 출발',
      area: '안덕면',
      email: 'test12@naver.com',
      img: 'img/bg1.jpg',
    },
    {
      id: 35,
      title: '남원에서 만나서 매주 오름 가보실분 구합니다',
      description: '남원에서 만나서 매주 주말에 ㄱㄱㄱㄱㄱㄱㄱㄱ',
      simpledec: '남원 만남 ㄱㄱ',
      area: '남원읍',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
    {
      id: 36,
      title: '남원에서 만나서 매주 오름 가보실분 구합니다',
      description: '남원에서 만나서 매주 주말에 ㄱㄱㄱㄱㄱㄱㄱㄱ',
      simpledec: '남원 만남 ㄱㄱ',
      area: '남원읍',
      email: 'test12@naver.com',
      img: 'img/bg2.jpg',
    },
  ],
});
